### ISSUE TITLE
use json_agg instead of chaining array_to_json(array_agg(row_to_json(table_attributes_filter)))

### ISSUE THREAD

**Issue by chollier** [DockYard/postgres_ext-serializers#10]
I've been playing a little bit with this gem, and looking at the queries I feel like we could avoid chaining array_to_json and array_agg and row_to_json 

and just use instead json_agg ( http://www.postgresql.org/docs/9.3/static/functions-aggregate.html )

well, writing that I just realized that it was a pg 9.3 feature.

Anyways I thought it could maybe simplify the code :wink:

**Comment by felixbuenemann** [comment]
Usage of `json_agg` was added in db578390 / PR #23.
