### ISSUE TITLE
Jbuilder

### ISSUE THREAD

**Issue by dsmithco** [dockyard/postgres_ext-serializers#15]
Can postgres_ext-serializers work with jbuilder?

**Comment by danmcclain** [comment]
Under further consideration, I want to move this away from AMS, but use AMS styled syntax. At the same time, we'll likely not support jbuilder.

**Comment by chollier** [comment]
@danmcclain I'm curious, could you elaborate on "move this away from AMS, but use AMS styled syntax" would this become a standalone feature / plugin, would we be still be able to plug it on AMS ?

**Comment by danmcclain** [comment]
@chollier The *tentative* plan is to make postgres_ext-serializers a standalone feature. With that in mind, I am a fan of the way that AMS declares their serialization, so I plan to have it follow that format.
