### ISSUE TITLE
relation "" does not exist error

### ISSUE THREAD

**Issue by mcm-ham** [dockyard/postgres_ext-serializers#19]
I keep getting this error when serializing child relationships:
```sql
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "" does not exist
LINE 5:                WHERE a.attrelid = '""'::regclass
                                          ^
SELECT a.attname, format_type(a.atttypid, a.atttypmod),
     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
FROM pg_attribute a LEFT JOIN pg_attrdef d
  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attrelid = '""'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
```
It only happens the first time after the app starts, subsequent times it's fine. It seems to be caused by `relation_query.dup.arel_table.name` being an empty string but `relation_query.arel_table.name` is fine. Not sure why `.dup` is used but removing it fixes this issue, or just simply calling `relation_query.arel_table` before `relation_query.dup` also fixes it.

**Comment by danmcclain** [comment]
Fixed by #23
