### ISSUE TITLE
Link reference materials in README.

### ISSUE THREAD

**Issue by rwjblue** [DockYard/postgres_ext-serializers#24]
http://reefpoints.dockyard.com/2014/05/27/avoid-rails-when-generating-json-responses-with-postgresql.html
https://www.youtube.com/watch?v=tYTw3Jshrqo

**Comment by felixbuenemann** [comment]
New URL: https://dockyard.com/blog/2014/05/27/avoid-rails-when-generating-json-responses-with-postgresql

**Comment by felixbuenemann** [comment]
Added to "How does it work?" section in the README.
