### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by felixbuenemann** [DockYard/postgres_ext-serializers#37]
@danmcclain I have lot's of bugfixes in my fork that I could contribute back. So I'm wondering if this gem is still maintained.

**Comment by bcardarella** [comment]
@felixbuenemann we are no longer using rails, so no it is not actively maintained. If you're up for it, and if @danmcclain is open to it, would you like to take it over?

**Comment by felixbuenemann** [comment]
I'd be willing to maintain this.

**Comment by bcardarella** [comment]
@danmcclain ping

**Comment by danmcclain** [comment]
👍🏼👍🏼

**Comment by bcardarella** [comment]
@felixbuenemann you should be added as a collaborator now. Closing. Dan will have to add you to push to rubygems

**Comment by felixbuenemann** [comment]
@bcardarella Great. I'll try to merge my changes via PRs over the next week or so and then look into cleaning up the open issues and PRs. After that I'll look into the existing forks to see what makes sense to be merged back here. I'm pretty busy working on a large project, so it'll take some time…

**Comment by bcardarella** [comment]
Sounds good, thank you very much for volunteering!

**Comment by felixbuenemann** [comment]
@danmcclain Please remember to add me as gem owner on rubygems, so I can push new versions. I'm using the same username as on github.

**Comment by danmcclain** [comment]
@felixbuenemann Should be an owner now
